<Project ToolsVersion="15.0" Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>ChurchReport</AssemblyName>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="wwwroot\**\*;Views\**\*;Areas\**\Views;appsettings.json;web.config">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <None Remove="Views\Home\BindingResultView.cshtml" />
    <None Remove="Views\Home\DedicationView.cshtml" />
    <None Remove="Views\Home\DisplayErrorView.cshtml" />
    <None Remove="Views\Home\FeeManagerView.cshtml" />
    <None Remove="Views\Home\FeeView.cshtml" />
    <None Remove="Views\Home\HappyGroupWeeklyReport.cshtml" />
    <None Remove="Views\Home\IntegrateView.cshtml" />
    <None Remove="Views\Home\LineIdLoginView - 沒有按鈕.cshtml" />
    <None Remove="Views\Home\LineIdLoginView.cshtml" />
    <None Remove="Views\Home\LineLiffView.cshtml" />
    <None Remove="Views\Home\MultiGroupView.cshtml" />
    <None Remove="Views\Home\PersonalReport - 尚未以群組方式顯示.cshtml" />
    <None Remove="Views\Home\PersonalReport.cshtml" />
    <None Remove="Views\Home\PresentView.cshtml" />
    <None Remove="Views\Home\QrCodeView.cshtml" />
    <None Remove="Views\Home\QualificationView.cshtml" />
    <None Remove="Views\Home\SchedulerView.cshtml" />
    <None Remove="Views\Home\SmallGroupQrCodeView.cshtml" />
    <None Remove="Views\Home\SundayQrCodeView.cshtml" />
    <None Remove="Views\Home\View - 複製.cshtml" />
    <None Remove="wwwroot\assets\images\永和堂牧養系統web_banner-01.jpg" />
    <None Remove="wwwroot\css\MasterDetail.css" />
    <None Remove="wwwroot\css\Site - 複製.css" />
    <None Remove="wwwroot\js\devextreme\devextreme-intl.min.js" />
    <None Remove="wwwroot\js\devextreme\localization\dx.messages.zh-tw.js" />
    <None Remove="wwwroot\js\FeeDataGridAjax.js" />
    <Content Include="bower.json" />
    <Content Include="Properties\launchSettings.json" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Crm.Sdk.Proxy">
      <HintPath>..\..\Dynamics 365 SDK DLL\Microsoft.Crm.Sdk.Proxy.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Xrm.Sdk">
      <HintPath>..\..\Dynamics 365 SDK DLL\Microsoft.Xrm.Sdk.dll</HintPath>
    </Reference>
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IIS" Version="2.2.6" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="2.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
    <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="8.2.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink.Loader" Version="14.1.0" />
    <PackageReference Include="DevExtreme.AspNet.Data" Version="2.5.1" />
    <PackageReference Include="DevExtreme.AspNet.Core" Version="19.2.6" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="BundlerMinifier.Core">
      <Version>2.2.301</Version>
    </DotNetCliToolReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Line.Messaging\Line.Messaging.csproj" />
    <ProjectReference Include="..\LineMessagingProcessor\LineMessagingProcessor.csproj" />
    <ProjectReference Include="..\LinePayCSharp\LinePayCSharp.csproj" />
    <ProjectReference Include="..\ToolUtility\ToolUtility.csproj" />
  </ItemGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
  </PropertyGroup>
  <Target Name="PostpublishScript" AfterTargets="Publish" Condition=" '$(IsCrossTargetingBuild)' != 'true' " />
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties DismissedDevExtremeVersion="" />
    </VisualStudio>
  </ProjectExtensions>
</Project>