// ============================================================================
// AI-繁體中文檔案註解
// 檔案路徑：Line.Messaging/Webhooks/Beacon.cs
// 所屬區塊：LINE Messaging SDK 封裝層，定義 LINE API DTO、Client 呼叫與訊息模型。
// 檔案責任：此檔案位於 LINE 或 RichMenu 相關流程，註解重點在說明 LINE API 契約、使用者狀態、通知副作用與 workflow 串接方式。
// 主要型別：class Beacon
// 主要成員：Hwid、Type、Dm
// 引用命名空間：未宣告 using；請由命名空間、同檔型別或完全限定名稱判讀相依性。
// 閱讀路徑：閱讀此檔案時應先確認 LINE userId/groupId/roomId、replyToken、push/reply API、RichMenu alias 與使用者狀態是否保持正確對應。
// 維護重點：後續修改時應先理解既有呼叫端與外部系統契約，避免把註解整理誤變成行為重構。
// 行為保護：本註解僅補充設計意圖與維護脈絡，不應改變任何執行流程、資料格式、序列化結果或外部 API 契約。
// 編碼要求：本檔案需維持 UTF-8 without BOM 與 CRLF，以符合專案 .editorconfig 與 Windows/Visual Studio 工作流。
// ============================================================================
namespace Line.Messaging.Webhooks
{
    /// <summary>
    /// Line Beacon
    /// </summary>
    public class Beacon
    {
        /// <summary>
        /// Hardware ID of the beacon that was detected
        /// </summary>
        public string Hwid { get; }

        /// <summary>
        /// Type of beacon event
        /// </summary>
        public BeaconType Type { get; }

        /// <summary>
        /// Optional. Device message of beacon that was detected
        /// The "device message" consists of data generated by the beacon to send notifications to bots. The beacon.dm property is only included in webhooks from devices that support the "device message" property. You can use beacon.dm with the LINE Simple Beacon specification. For more information, see the LINE Simple Beacon specification.
        /// </summary>
        public string Dm { get; }

        public Beacon(string hwid, BeaconType type, string dm)
        {
            Hwid = hwid;
            Type = type;
            Dm = dm;
        }
    }
}
