<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>LineMessagingProcessor</RootNamespace>
    <AssemblyName>LineMessagingProcessor</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);CS8602;CS8603</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Configuration\**" />
    <Compile Remove="DependencyInjection\**" />
    <Compile Remove="Facades\**" />
    <Compile Remove="Factory\**" />
    <Compile Remove="Interfaces\**" />
    <Compile Remove="Models\**" />
    <Compile Remove="Services\**" />
    <EmbeddedResource Remove="Configuration\**" />
    <EmbeddedResource Remove="DependencyInjection\**" />
    <EmbeddedResource Remove="Facades\**" />
    <EmbeddedResource Remove="Factory\**" />
    <EmbeddedResource Remove="Interfaces\**" />
    <EmbeddedResource Remove="Models\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Configuration\**" />
    <None Remove="DependencyInjection\**" />
    <None Remove="Facades\**" />
    <None Remove="Factory\**" />
    <None Remove="Interfaces\**" />
    <None Remove="Models\**" />
    <None Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
  </ItemGroup>

</Project>
