<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>LineMessagingProcessor</RootNamespace>
    <AssemblyName>LineMessagingProcessor</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);CS8602;CS8603</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configuration\" />
    <Folder Include="DependencyInjection\" />
    <Folder Include="Facades\" />
    <Folder Include="Factory\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Models\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
